Feature/5359 test files group 15
US-EPA-CAMD/easey-ecmps-ui pull request #1196
Opened 2023-07-26 18:48 UTC by cw-cvp

2023-07-26 20:52 UTC, addisgmichael requested changes
Standardize
- use reusable renderer from src/mocks/render.js
- use constants.js and functions.js under src/mocks to populate mock data

2023-07-27 14:02 UTC, cw-cvp commented
> Standardize
> 
> * use reusable renderer from src/mocks/render.js
> * use constants.js and functions.js under src/mocks to populate mock data

changes made

2023-07-27 15:03 UTC, addisgmichael commented on src/components/export/Export/Export.test.js
> +    render(
render function is already wrapped with act and a provider if you pass in store. you can just call it this way
 await render(<Export {...props}/>, store)

2023-07-27 15:59 UTC, addisgmichael approved these changes

2023-07-27 15:59 UTC, merged