fix:offline message as per the content
US-EPA-CAMD/easey-ecmps-ui pull request #1504
Opened 2024-10-31 22:06 UTC by ergjustin

## Ticket
[Add the ability to take ECMPS offline](https://github.com/US-EPA-CAMD/easey-ui/issues/6243)

2024-11-12 18:22 UTC, maxdiebold-erg requested changes
All looks good! I did get one failing unit test, noted below.

2024-11-12 18:22 UTC, maxdiebold-erg commented on src/utils/api/qaCertificationsAPI.js
> +import { secureAxios } from "./easeyAuthApi"
This change is causing `qaCertificationAPI.test.js` to fail for me, since `refreshClientToken` is called even if `ecmpsUser` is null.

I think you could change occurrences of `expect(mock.history.get.length).toBe(1);` to `expect(mock.history.get.length).toBe(2);` or, alternatively, move the `refreshClientToken` call inside the `if (ecmpsUser) {` block.

2024-12-09 21:46 UTC, ergjustin commented on src/utils/api/qaCertificationsAPI.js
> +import { secureAxios } from "./easeyAuthApi"
I had an issue in my local environment, fixed it, and pushed it to GitHub([link](https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1504/commits/bc0183c74d660a888f40872b7aa76a7917138d4c)). But GitHub threw an error, so I reverted the changes([link](https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1504/commits/9092edc048c77fed3a02d5ab59320c5ddaab9875)). Now everything's working smoothly again.

2024-12-09 21:48 UTC, mark-hayward-erg approved these changes

2024-12-09 21:49 UTC, maxdiebold-erg approved these changes

2024-12-09 21:51 UTC, merged